const fs = require('fs');
const path = require('path');

const translationsRemaining = {
  "th": {
    "physics_section": "⚡ ฟิสิกส์และไดนามิกการชน",
    "enable_physics": "เปิดใช้งานเอ็นจิ้นฟิสิกส์ (แรงโน้มถ่วงและการขว้าง)",
    "physics_floor": "เปิดใช้งานการชนพื้น",
    "physics_gravity": "แรงโน้มถ่วง",
    "physics_elasticity": "ความยืดหยุ่น / การเด้ง",
    "physics_hint_title": "ทางลัดการขว้างทางฟิสิกส์",
    "physics_hint_body": "กด D ค้างไว้ + ลากเมาส์ซ้ายเพื่อขว้างด้วยแรงเหวี่ยง!",
    "fps_mode_section": "🎥 มุมมองบุคคลที่หนึ่งและพิกัดอวกาศ",
    "enable_fps_mode": "เปิดใช้งานโหมดกล้องบุคคลที่หนึ่ง",
    "fps_sub": "(สลับด้วย Ctrl + Shift + F)",
    "fps_hint_title": "การควบคุม FPS",
    "fps_hint_body": "เลื่อนเมาส์เพื่อดู 360° WASD เพื่อย้าย, Space (ขึ้น), Shift (ลง) กด ESC เพื่อออก!",
    "reset_camera": "รีเซ็ตกล้องและตำแหน่ง 🔄",
    "show_xyz_coords": "เปิดใช้งาน HUD พิกัด Spatial XYZ สด",
    "show_xyz_sub": "(สลับด้วย Ctrl + Shift + C)",
    "show_ground_grid": "แสดงเส้นตารางอ้างอิงพื้นที่ 3D",
    "xyz_hud_title": "📐 พิกัดอวกาศ XYZ",
    "spotlight_section": "🔦 ควบคุมสปอตไลท์เวทีหลายแหล่ง",
    "enable_spotlight": "เปิดใช้งานแหล่งสปอตไลท์",
    "spotlight_angle_h": "มุมวงโคจรแนวนอน",
    "spotlight_angle_v": "มุมความสูงแนวตั้ง",
    "spotlight_cone": "มุมกรวยลำแสง",
    "spotlight_intensity": "ความเข้มสปอตไลท์",
    "spotlight_color": "สีสปอตไลท์",
    "spotlight_color_white": "ขาวบริสุทธิ์",
    "spotlight_color_gold": "ทองอบอุ่นคอนเสิร์ต",
    "spotlight_color_cyan": "ไซเบอร์พังก์นีออนไซแอน",
    "spotlight_color_pink": "ชมพูเวที",
    "spotlight_color_red": "แดงเลเซอร์",
    "enable_studio_lights": "เปิดใช้งานแสงโดยรอบสตูดิโอ",
    "ambient_intensity": "ความสว่างแสงโดยรอบหลัก",
    "dark_stage_preset": "🎭 โหมดเวทีมืด",
    "add_spotlight": "➕ เพิ่มแหล่งสปอตไลท์",
    "remove_spotlight": "🗑️ ลบสปอตไลท์",
    "spotlight_num": "สปอตไลท์",
    "dual_concert_preset": "🎸 สปอตไลท์คู่คอนเสิร์ต (ทอง + ไซแอน)",
    "max_spotlights_reached": "ถึงขีดจำกัดสูงสุด 4 สปอตไลท์แล้ว!",
    "tab_display": "🎯 การแสดงผลและโมเดล",
    "tab_motion": "🌀 การเคลื่อนไหวและการหมุน",
    "tab_lighting": "🔦 แสงเวที",
    "tab_physics": "⚡ เอ็นจิ้นฟิสิกส์",
    "tab_camera": "🎥 กล้องและอวกาศ",
    "tab_system": "⚙️ ระบบและภาษา",
    "drag_hint": "⠿ ลากเพื่อย้ายตำแหน่ง",
    "nav_prev_tab": "แท็บก่อนหน้า / สกรูลซ้าย",
    "nav_next_tab": "แท็บถัดไป / สกรูลขวา"
  },
  "id": {
    "physics_section": "⚡ Fisika & Dinamika Tabrakan",
    "enable_physics": "Aktifkan Mesin Fisika (Gravitasi & Lemparan)",
    "physics_floor": "Aktifkan Kolider Lantai Ground",
    "physics_gravity": "Gravitasi",
    "physics_elasticity": "Elastisitas / Pantulan",
    "physics_hint_title": "Pintasan Lemparan Fisika",
    "physics_hint_body": "Tahan D + Seret Klik Kiri untuk melempar dengan momentum!",
    "fps_mode_section": "🎥 Perspektif Orang Pertama & Koordinat Spasial",
    "enable_fps_mode": "Aktifkan Mode Kamera Orang Pertama",
    "fps_sub": "(Beralih dengan Ctrl + Shift + F)",
    "fps_hint_title": "Kontrol FPS",
    "fps_hint_body": "Gerakkan mouse untuk melihat 360°. WASD untuk bergerak, Spasi (Naik), Shift (Turun). ESC untuk keluar!",
    "reset_camera": "Reset Kamera & Posisi Mascot 🔄",
    "show_xyz_coords": "Aktifkan HUD Koordinat Spasial XYZ",
    "show_xyz_sub": "(Beralih dengan Ctrl + Shift + C)",
    "show_ground_grid": "Tampilkan Kisi Referensi Spasial 3D",
    "xyz_hud_title": "📐 Koordinat Spasial XYZ",
    "spotlight_section": "🔦 Kontrol Lampu Sorot Panggung Multi-Sumber",
    "enable_spotlight": "Aktifkan Sumber Lampu Sorot",
    "spotlight_angle_h": "Sudut Orbit Horizontal",
    "spotlight_angle_v": "Sudut Elevasi Vertikal",
    "spotlight_cone": "Sudut Kerucut Sinar",
    "spotlight_intensity": "Intensitas Lampu Sorot",
    "spotlight_color": "Warna Lampu Sorot",
    "spotlight_color_white": "Putih Murni",
    "spotlight_color_gold": "Emas Hangat Konser",
    "spotlight_color_cyan": "Sian Neon Cyberpunk",
    "spotlight_color_pink": "Merah Muda Panggung",
    "spotlight_color_red": "Merah Laser",
    "enable_studio_lights": "Aktifkan Pencahayaan Sekitar Studio",
    "ambient_intensity": "Kecerahan Cahaya Sekitar Utama",
    "dark_stage_preset": "🎭 Mode Panggung Gelap",
    "add_spotlight": "➕ Tambah Sumber Lampu Sorot",
    "remove_spotlight": "🗑️ Hapus Lampu Sorot",
    "spotlight_num": "Lampu Sorot",
    "dual_concert_preset": "🎸 Lampu Sorot Ganda Konser (Emas + Sian)",
    "max_spotlights_reached": "Batas maksimum 4 lampu sorot tercapai!",
    "tab_display": "🎯 Tampilan & Model",
    "tab_motion": "🌀 Gerakan & Putaran",
    "tab_lighting": "🔦 Pencahayaan Panggung",
    "tab_physics": "⚡ Mesin Fisika",
    "tab_camera": "🎥 Kamera & Spasial",
    "tab_system": "⚙️ Sistem & Bahasa",
    "drag_hint": "⠿ Seret untuk memindahkan",
    "nav_prev_tab": "Tab Sebelumnya / Gulir Kiri",
    "nav_next_tab": "Tab Berikutnya / Gulir Kanan"
  },
  "ms": {
    "physics_section": "⚡ Fizik & Dinamik Pelanggaran",
    "enable_physics": "Dayakan Enjin Fizik (Graviti & Lemparan)",
    "physics_floor": "Dayakan Pengesan Lantai Ground",
    "physics_gravity": "Graviti",
    "physics_elasticity": "Keanjalan / Lantikan",
    "physics_hint_title": "Pintas Lemparan Fizik",
    "physics_hint_body": "Tahan D + Seret Klik Kiri untuk melempar dengan momentum!",
    "fps_mode_section": "🎥 Perspektif Orang Pertama & Koordinat Ruang",
    "enable_fps_mode": "Dayakan Mod Kamera Orang Pertama",
    "fps_sub": "(Tukar dengan Ctrl + Shift + F)",
    "fps_hint_title": "Kawalan FPS",
    "fps_hint_body": "Gerakkan tetikus untuk pandangan 360°. WASD untuk bergerak, Ruang (Naik), Shift (Turun). ESC untuk keluar!",
    "reset_camera": "Tetap Semula Kamera & Kedudukan 🔄",
    "show_xyz_coords": "Dayakan HUD Koordinat Ruang XYZ",
    "show_xyz_sub": "(Tukar dengan Ctrl + Shift + C)",
    "show_ground_grid": "Tunjukkan Grids Rujukan Ruang 3D",
    "xyz_hud_title": "📐 Koordinat Ruang XYZ",
    "spotlight_section": "🔦 Kawalan Lampu Sorot Pentas Pelbagai Sumber",
    "enable_spotlight": "Dayakan Sumber Lampu Sorot",
    "spotlight_angle_h": "Sudut Orbit Melintang",
    "spotlight_angle_v": "Sudut Ketinggian Menegak",
    "spotlight_cone": "Sudut Kon Alur Cahaya",
    "spotlight_intensity": "Keamatan Lampu Sorot",
    "spotlight_color": "Warna Lampu Sorot",
    "spotlight_color_white": "Putih Tulen",
    "spotlight_color_gold": "Emas Hangat Konsert",
    "spotlight_color_cyan": "Sian Neon Cyberpunk",
    "spotlight_color_pink": "Merah Jambu Pentas",
    "spotlight_color_red": "Merah Laser",
    "enable_studio_lights": "Dayakan Pencahayaan Sekitar Studio",
    "ambient_intensity": "Kecerahan Cahaya Sekitar Utama",
    "dark_stage_preset": "🎭 Mod Pentas Gelap",
    "add_spotlight": "➕ Tambah Sumber Lampu Sorot",
    "remove_spotlight": "🗑️ Buang Lampu Sorot",
    "spotlight_num": "Lampu Sorot",
    "dual_concert_preset": "🎸 Lampu Sorot Kembar Konsert (Emas + Sian)",
    "max_spotlights_reached": "Ahad maksimum 4 lampu sorot dicapai!",
    "tab_display": "🎯 Paparan & Model",
    "tab_motion": "🌀 Gerakan & Putaran",
    "tab_lighting": "🔦 Pencahayaan Pentas",
    "tab_physics": "⚡ Enjin Fizik",
    "tab_camera": "🎥 Kamera & Ruang",
    "tab_system": "⚙️ Sistem & Bahasa",
    "drag_hint": "⠿ Seret untuk alih",
    "nav_prev_tab": "Tab Terdahulu / Tatal Kiri",
    "nav_next_tab": "Tab Seterusnya / Tatal Kanan"
  },
  "cs": {
    "physics_section": "⚡ Fyzika a Dynamika Kolizí",
    "enable_physics": "Povolit Fyzikální Motor (Gravitace a Hody)",
    "physics_floor": "Povolit Kolizi s Podlahou",
    "physics_gravity": "Gravitace",
    "physics_elasticity": "Pružnost / Odraz",
    "physics_hint_title": "Zkratka pro Fyzikální Hod",
    "physics_hint_body": "Držte D + Tažení Levým Tlačítkem pro hod s hybností!",
    "fps_mode_section": "🎥 Pohled z První Osoby a Prostorové Souřadnice",
    "enable_fps_mode": "Povolit Režim Kamery z První Osoby",
    "fps_sub": "(Přepnout pomocí Ctrl + Shift + F)",
    "fps_hint_title": "Ovládání FPS",
    "fps_hint_body": "Pohybujte myší pro 360° pohled. WASD pro pohyb, Mezerník (Nahoru), Shift (Dolů). ESC pro ukončení!",
    "reset_camera": "Resetovat Kameru a Pozici 🔄",
    "show_xyz_coords": "Povolit HUD Prostorových Souřadnic XYZ",
    "show_xyz_sub": "(Přepnout pomocí Ctrl + Shift + C)",
    "show_ground_grid": "Zobrazit 3D Referenční Mřížku",
    "xyz_hud_title": "📐 Prostorové Souřadnice XYZ",
    "spotlight_section": "🔦 Ovládání Scénických Reflektorů",
    "enable_spotlight": "Povolit Zdroj Reflektoru",
    "spotlight_angle_h": "Horizontální Úhel Orbity",
    "spotlight_angle_v": "Vertikální Úhel Elevace",
    "spotlight_cone": "Úhel Kuželu Paprsku",
    "spotlight_intensity": "Intenzita Reflektoru",
    "spotlight_color": "Barva Reflektoru",
    "spotlight_color_white": "Čistá Bílá",
    "spotlight_color_gold": "Koncertní Teplé Zlato",
    "spotlight_color_cyan": "Cyberpunkový Neonový Azurová",
    "spotlight_color_pink": "Scénická Růžová",
    "spotlight_color_red": "Laserová Červená",
    "enable_studio_lights": "Povolit Okolní Osvětlení Studia",
    "ambient_intensity": "Jas Hlavního Okolního Světla",
    "dark_stage_preset": "🎭 Režim Tmavé Scény",
    "add_spotlight": "➕ Přidat Reflektor",
    "remove_spotlight": "🗑️ Odebrat Reflektor",
    "spotlight_num": "Reflektor",
    "dual_concert_preset": "🎸 Dvojitý Koncertní Reflektor (Zlato + Azurová)",
    "max_spotlights_reached": "Dosaženo maxima 4 reflektorů!",
    "tab_display": "🎯 Zobrazení a Model",
    "tab_motion": "🌀 Pohyb a Otáčení",
    "tab_lighting": "🔦 Osvětlení Scény",
    "tab_physics": "⚡ Fyzikální Motor",
    "tab_camera": "🎥 Kamera a Prostor",
    "tab_system": "⚙️ Systém a Jazyky",
    "drag_hint": "⠿ Tažením přesunete",
    "nav_prev_tab": "Předchozí Záložka / Posun Vlevo",
    "nav_next_tab": "Následující Záložka / Posun Vpravo"
  },
  "da": {
    "physics_section": "⚡ Fysik & Kollisionsdynamik",
    "enable_physics": "Aktiver Fysikmotor (Tyngdekraft & Kast)",
    "physics_floor": "Aktiver Gulvkollision",
    "physics_gravity": "Tyngdekraft",
    "physics_elasticity": "Elasticitet / Hop",
    "physics_hint_title": "Fysisk Kast Genvej",
    "physics_hint_body": "Hold D + Venstre-klik træk for at kaste med fremdrift!",
    "fps_mode_section": "🎥 Førstepersonsperspektiv & Rumlige Koordinater",
    "enable_fps_mode": "Aktiver Førstepersons Kameratilstand",
    "fps_sub": "(Skift med Ctrl + Shift + F)",
    "fps_hint_title": "FPS Betjening",
    "fps_hint_body": "Bevæg musen for 360° visning. WASD for at bevæge, Mellemrum (Op), Shift (Ned). ESC for at afslutte!",
    "reset_camera": "Nulstil Kamera & Position 🔄",
    "show_xyz_coords": "Aktiver Live Rumlige XYZ Koordinater HUD",
    "show_xyz_sub": "(Skift med Ctrl + Shift + C)",
    "show_ground_grid": "Vis 3D Gulv-referencenet",
    "xyz_hud_title": "📐 Rumlige XYZ Koordinater",
    "spotlight_section": "🔦 Scenespotlight Styring",
    "enable_spotlight": "Aktiver Spotlight Kilde",
    "spotlight_angle_h": "Vandret Orbitvinkel",
    "spotlight_angle_v": "Lodret Elevatiosvinkel",
    "spotlight_cone": "Lysstråle Keglevinkel",
    "spotlight_intensity": "Spotlight Intensitet",
    "spotlight_color": "Spotlight Farve",
    "spotlight_color_white": "Ren Hvid",
    "spotlight_color_gold": "Koncert Varm Guld",
    "spotlight_color_cyan": "Cyberpunk Neon Cyan",
    "spotlight_color_pink": "Scene Lyserød",
    "spotlight_color_red": "Laser Rød",
    "enable_studio_lights": "Aktiver Studio Omgivende Belysning",
    "ambient_intensity": "Hoved Omgivende Lysstyrke",
    "dark_stage_preset": "🎭 Mørk Scene Tilstand",
    "add_spotlight": "➕ Tilføj Spotlight",
    "remove_spotlight": "🗑️ Fjern Spotlight",
    "spotlight_num": "Spotlight",
    "dual_concert_preset": "🎸 Koncert Dobbelt Spotlight (Guld + Cyan)",
    "max_spotlights_reached": "Maksimum 4 spotlights nået!",
    "tab_display": "🎯 Visning & Model",
    "tab_motion": "🌀 Bevægelse & Spin",
    "tab_lighting": "🔦 Scenebelysning",
    "tab_physics": "⚡ Fysikmotor",
    "tab_camera": "🎥 Kamera & Rum",
    "tab_system": "⚙️ System & Sprog",
    "drag_hint": "⠿ Træk for at flytte",
    "nav_prev_tab": "Forrige Fane / Rul Venstre",
    "nav_next_tab": "Næste Fane / Rul Højre"
  },
  "fi": {
    "physics_section": "⚡ Fysiikka ja Törmäysdynamiikka",
    "enable_physics": "Ota Fysiikkamoottori Käyttöön (Painovoima ja Heitto)",
    "physics_floor": "Ota Lattiattörmäin Käyttöön",
    "physics_gravity": "Painovoima",
    "physics_elasticity": "Kimmous / Bounssi",
    "physics_hint_title": "Fysiikkanen Heitto Pikakuvake",
    "physics_hint_body": "Pidä D + Vasen Klikkaus Vedä heittääksesi vauhdilla!",
    "fps_mode_section": "🎥 Ensimmäisen Persoonan Perspektiivi & Koordinaatit",
    "enable_fps_mode": "Ota Ensimmäisen Persoonan Kameratila Käyttöön",
    "fps_sub": "(Vaihda näppäimillä Ctrl + Shift + F)",
    "fps_hint_title": "FPS-Ohjaimet",
    "fps_hint_body": "Liikuta hiirtä katsoaksesi 360°. WASD liikkumiseen, Välilyönti (Ylös), Shift (Alas). ESC poistuaksesi!",
    "reset_camera": "Nollaa Kamera ja Sijainti 🔄",
    "show_xyz_coords": "Ota Reaaliaikaiset XYZ-Koordinaatit Käyttöön",
    "show_xyz_sub": "(Vaihda näppäimillä Ctrl + Shift + C)",
    "show_ground_grid": "Näytä 3D-Lattiaruudukko",
    "xyz_hud_title": "📐 Tilan XYZ-Koordinaatit",
    "spotlight_section": "🔦 Näyttämön Kohdevalojen Ohjaus",
    "enable_spotlight": "Ota Kohdevalo Käyttöön",
    "spotlight_angle_h": "Vaakasuora Kiertokulma",
    "spotlight_angle_v": "Pystysuora Korkeuskulma",
    "spotlight_cone": "Valokeilan Kartiokulma",
    "spotlight_intensity": "Kohdevalon Voimakkuus",
    "spotlight_color": "Kohdevalon Väri",
    "spotlight_color_white": "Puhdas Valkoinen",
    "spotlight_color_gold": "Konsertin Lämmin Kulta",
    "spotlight_color_cyan": "Cyberpunk Neon Syaani",
    "spotlight_color_pink": "Näyttämön Vaaleanpunainen",
    "spotlight_color_red": "Laser Punainen",
    "enable_studio_lights": "Ota Studion Ympäristövalo Käyttöön",
    "ambient_intensity": "Ympäristövalon Kirkkaus",
    "dark_stage_preset": "🎭 Pimeä Näyttämö -Tila",
    "add_spotlight": "➕ Lisää Kohdevalo",
    "remove_spotlight": "🗑️ Poista Kohdevalo",
    "spotlight_num": "Kohdevalo",
    "dual_concert_preset": "🎸 Konsertin Kaksoiskohdevalo (Kulta + Syaani)",
    "max_spotlights_reached": "Enintään 4 kohdevaloa saavutettu!",
    "tab_display": "🎯 Näyttö ja Malli",
    "tab_motion": "🌀 Liike ja Pyöritys",
    "tab_lighting": "🔦 Näyttämön Valaistus",
    "tab_physics": "⚡ Fysiikkamoottori",
    "tab_camera": "🎥 Kamera ja Tila",
    "tab_system": "⚙️ Järjestelmä ja Kielet",
    "drag_hint": "⠿ Vedä siirtääksesi",
    "nav_prev_tab": "Edellinen Välilehti / Selaa Vasemmalle",
    "nav_next_tab": "Seuraava Välilehti / Selaa Oikealle"
  },
  "sv": {
    "physics_section": "⚡ Fysik & Kollisionsdynamik",
    "enable_physics": "Aktivera Fysikmotor (Tyngdkraft & Kast)",
    "physics_floor": "Aktivera Golvkollision",
    "physics_gravity": "Tyngdkraft",
    "physics_elasticity": "Elasticitet / Studs",
    "physics_hint_title": "Fysiskt Kast Genväg",
    "physics_hint_body": "Håll D + Vänsterklicka Dra för att kasta med rörelsemängd!",
    "fps_mode_section": "🎥 Förstapersonsperspektiv & Rumsliga Koordinater",
    "enable_fps_mode": "Aktivera Första Persons Kameraläge",
    "fps_sub": "(Växla med Ctrl + Shift + F)",
    "fps_hint_title": "FPS-Kontroller",
    "fps_hint_body": "Rör musen för 360° vinkel. WASD för att röra dig, Blanksteg (Upp), Shift (Ner). ESC för att avsluta!",
    "reset_camera": "Återställ Kamera & Position 🔄",
    "show_xyz_coords": "Aktivera Live Rumsliga XYZ-Koordinater HUD",
    "show_xyz_sub": "(Växla med Ctrl + Shift + C)",
    "show_ground_grid": "Visa 3D-Golvreferensnät",
    "xyz_hud_title": "📐 Rumsliga XYZ-Koordinater",
    "spotlight_section": "🔦 Scen-Spotlight-Styrning",
    "enable_spotlight": "Aktivera Spotlight-Källa",
    "spotlight_angle_h": "Horisontell Omloppsvinkel",
    "spotlight_angle_v": "Vertikal Höjdvinkel",
    "spotlight_cone": "Ljusstrålekonvinkel",
    "spotlight_intensity": "Spotlight-Intensitet",
    "spotlight_color": "Spotlight-Färg",
    "spotlight_color_white": "Ren Vit",
    "spotlight_color_gold": "Konsert Varmt Guld",
    "spotlight_color_cyan": "Cyberpunk Neon Cyan",
    "spotlight_color_pink": "Scen Rosa",
    "spotlight_color_red": "Laser Röd",
    "enable_studio_lights": "Aktivera Studio-Omgivningsljus",
    "ambient_intensity": "Huvud-Omgivningsljusstyrka",
    "dark_stage_preset": "🎭 Mörk Scen Läge",
    "add_spotlight": "➕ Lägg till Spotlight",
    "remove_spotlight": "🗑️ Ta bort Spotlight",
    "spotlight_num": "Spotlight",
    "dual_concert_preset": "🎸 Konsert Dubbel Spotlight (Guld + Cyan)",
    "max_spotlights_reached": "Maximalt 4 spotlights uppnått!",
    "tab_display": "🎯 Visning & Modell",
    "tab_motion": "🌀 Rörelse & Spin",
    "tab_lighting": "🔦 Scenbelysning",
    "tab_physics": "⚡ Fysikmotor",
    "tab_camera": "🎥 Kamera & Rum",
    "tab_system": "⚙️ System & Språk",
    "drag_hint": "⠿ Dra för att flytta",
    "nav_prev_tab": "Föregående Flik / Bläddra Vänster",
    "nav_next_tab": "Nästa Flik / Bläddra Höger"
  },
  "no": {
    "physics_section": "⚡ Fysikk & Kollisjonsdynamikk",
    "enable_physics": "Aktiver Fysikkmotor (Tyngdekraft & Kast)",
    "physics_floor": "Aktiver Gulvkollisjon",
    "physics_gravity": "Tyngdekraft",
    "physics_elasticity": "Elastisitet / Spretteevne",
    "physics_hint_title": "Fysisk Kast Snarvei",
    "physics_hint_body": "Hold D + Venstreklikk Dra for å kaste med fremdrift!",
    "fps_mode_section": "🎥 Førstepersonsperspektiv & Romlige Koordinater",
    "enable_fps_mode": "Aktiver Førstepersons Kameramodus",
    "fps_sub": "(Veksle med Ctrl + Shift + F)",
    "fps_hint_title": "FPS Kontroller",
    "fps_hint_body": "Beveg musen for 360° visning. WASD for å bevege deg, Mellomrom (Opp), Shift (Ned). ESC for å avslutte!",
    "reset_camera": "Tilbakestill Kamera & Posisjon 🔄",
    "show_xyz_coords": "Aktiver Live Romlige XYZ Koordinater HUD",
    "show_xyz_sub": "(Veksle med Ctrl + Shift + C)",
    "show_ground_grid": "Vis 3D-Gulvreferansenett",
    "xyz_hud_title": "📐 Romlige XYZ-Koordinater",
    "spotlight_section": "🔦 Scenespotlight-Styring",
    "enable_spotlight": "Aktiver Spotlight-Kilde",
    "spotlight_angle_h": "Vannrett Banevinkel",
    "spotlight_angle_v": "Loddrett Høydevinkel",
    "spotlight_cone": "Lysstrålekjeglevinkel",
    "spotlight_intensity": "Spotlight-Intensitet",
    "spotlight_color": "Spotlight-Farge",
    "spotlight_color_white": "Ren Hvit",
    "spotlight_color_gold": "Konsert Varmt Gull",
    "spotlight_color_cyan": "Cyberpunk Neon Cyan",
    "spotlight_color_pink": "Scene Rosa",
    "spotlight_color_red": "Laser Rød",
    "enable_studio_lights": "Aktiver Studio-Omgivelseslys",
    "ambient_intensity": "Hoved-Omgivelseslysstyrke",
    "dark_stage_preset": "🎭 Mørk Scene Modus",
    "add_spotlight": "➕ Legg til Spotlight",
    "remove_spotlight": "🗑️ Fjern Spotlight",
    "spotlight_num": "Spotlight",
    "dual_concert_preset": "🎸 Konsert Dobbel Spotlight (Gull + Cyan)",
    "max_spotlights_reached": "Maksimalt 4 spotlights nådd!",
    "tab_display": "🎯 Visning & Modell",
    "tab_motion": "🌀 Bevegelse & Spinn",
    "tab_lighting": "🔦 Scenebelysning",
    "tab_physics": "⚡ Fysikkmotor",
    "tab_camera": "🎥 Kamera & Rom",
    "tab_system": "⚙️ System & Språk",
    "drag_hint": "⠿ Dra for å flytte",
    "nav_prev_tab": "Forrige Fane / Rull Venstre",
    "nav_next_tab": "Neste Fane / Rull Høyre"
  },
  "hu": {
    "physics_section": "⚡ Fizika és Ütközési Dinamika",
    "enable_physics": "Fizikai Motor Engedélyezése (Gravitáció és Dobás)",
    "physics_floor": "Padlóütköző Engedélyezése",
    "physics_gravity": "Gravitáció",
    "physics_elasticity": "Rugalmasság / Pattogás",
    "physics_hint_title": "Fizikai Dobás Billentyűparancs",
    "physics_hint_body": "Tartsa lenyomva a D billentyűt + Bal Húzás a dobáshoz!",
    "fps_mode_section": "🎥 Első Személyű Nézet és Térbeli Koordináták",
    "enable_fps_mode": "Első Személyű Kameramód Engedélyezése",
    "fps_sub": "(Váltás Ctrl + Shift + F billentyűkkel)",
    "fps_hint_title": "FPS Vezérlők",
    "fps_hint_body": "Mozgassa az egeret a 360°-os nézethez. WASD a mozgáshoz, Szóköz (Fel), Shift (Le). ESC a kilépéshez!",
    "reset_camera": "Kamera és Pozíció Visszaállítása 🔄",
    "show_xyz_coords": "Élő Térbeli XYZ Koordináták HUD Engedélyezése",
    "show_xyz_sub": "(Váltás Ctrl + Shift + C billentyűkkel)",
    "show_ground_grid": "3D Padló Referenciarács Megjelenítése",
    "xyz_hud_title": "📐 Térbeli XYZ Koordináták",
    "spotlight_section": "🔦 Színpadi Reflektorok Vezérlése",
    "enable_spotlight": "Reflektorforrás Engedélyezése",
    "spotlight_angle_h": "Vízszintes Pályaszög",
    "spotlight_angle_v": "Függőleges Magassági Szög",
    "spotlight_cone": "Fénysugár Kúpszög",
    "spotlight_intensity": "Reflektor Intenzitás",
    "spotlight_color": "Reflektor Színe",
    "spotlight_color_white": "Tiszta Fehér",
    "spotlight_color_gold": "Koncert Meleg Arany",
    "spotlight_color_cyan": "Cyberpunk Neon Ciánkék",
    "spotlight_color_pink": "Színpadi Rózsaszín",
    "spotlight_color_red": "Lézer Piros",
    "enable_studio_lights": "Stúdió Környezeti Fény Engedélyezése",
    "ambient_intensity": "Fő Környezeti Fényerő",
    "dark_stage_preset": "🎭 Sötét Színpad Mód Beállítása",
    "add_spotlight": "➕ Reflektor Hozzáadása",
    "remove_spotlight": "🗑️ Reflektor Eltávolítása",
    "spotlight_num": "Reflektor",
    "dual_concert_preset": "🎸 Koncert Dupla Reflektor (Arany + Ciánkék)",
    "max_spotlights_reached": "Elérte a maximális 4 reflektort!",
    "tab_display": "🎯 Megjelenítés és Modell",
    "tab_motion": "🌀 Mozgás és Forgatás",
    "tab_lighting": "🔦 Színpadi Világítás",
    "tab_physics": "⚡ Fizikai Motor",
    "tab_camera": "🎥 Kamera és Tér",
    "tab_system": "⚙️ Rendszer és Nyelvek",
    "drag_hint": "⠿ Húzza a mozgatáshoz",
    "nav_prev_tab": "Előző Lap / Görgetés Balra",
    "nav_next_tab": "Következő Lap / Görgetés Jobbra"
  },
  "ro": {
    "physics_section": "⚡ Fizică și Dinamică de Coliziune",
    "enable_physics": "Activează Motorul Fizic (Gravitație și Aruncare)",
    "physics_floor": "Activează Coliziunea cu Podeaua",
    "physics_gravity": "Gravitație",
    "physics_elasticity": "Elasticitate / Ricoșeu",
    "physics_hint_title": "Scurtătură Aruncare Fizică",
    "physics_hint_body": "Ține apăsat D + Trage Click Stânga pentru aruncare cu impuls!",
    "fps_mode_section": "🎥 Perspectivă First-Person și Coordonate Spațiale",
    "enable_fps_mode": "Activează Modul Cameră First-Person",
    "fps_sub": "(Comută cu Ctrl + Shift + F)",
    "fps_hint_title": "Controale FPS",
    "fps_hint_body": "Mișcă mouse-ul pentru privire 360°. WASD pentru deplasare, Spațiu (Sus), Shift (Jos). ESC pentru ieșire!",
    "reset_camera": "Resetează Camera și Poziția 🔄",
    "show_xyz_coords": "Activează Afișajul HUD Coordonate XYZ",
    "show_xyz_sub": "(Comută cu Ctrl + Shift + C)",
    "show_ground_grid": "Afișează Grila 3D de Referință",
    "xyz_hud_title": "📐 Coordonate Spațiale XYZ",
    "spotlight_section": "🔦 Control Reflectoare Scenă Multi-Sursă",
    "enable_spotlight": "Activează Sursa Reflector",
    "spotlight_angle_h": "Unghi Orbită Orizontală",
    "spotlight_angle_v": "Unghi Elevație Verticală",
    "spotlight_cone": "Unghi Con Fascicul",
    "spotlight_intensity": "Intensitate Reflector",
    "spotlight_color": "Culoare Reflector",
    "spotlight_color_white": "Alb Pur",
    "spotlight_color_gold": "Auriu Cald Concert",
    "spotlight_color_cyan": "Cian Neon Cyberpunk",
    "spotlight_color_pink": "Roz Scenă",
    "spotlight_color_red": "Roșu Laser",
    "enable_studio_lights": "Activează Iluminarea Ambientală Studio",
    "ambient_intensity": "Luminozitate Ambientală Principală",
    "dark_stage_preset": "🎭 Mod Scenă Întunecată",
    "add_spotlight": "➕ Adaugă Reflector",
    "remove_spotlight": "🗑️ Șterge Reflector",
    "spotlight_num": "Reflector",
    "dual_concert_preset": "🎸 Reflector Dublu Concert (Auriu + Cian)",
    "max_spotlights_reached": "Limita maximă de 4 reflectoare a fost atinsă!",
    "tab_display": "🎯 Afișaj și Model",
    "tab_motion": "🌀 Mișcare și Rotire",
    "tab_lighting": "🔦 Iluminat Scenă",
    "tab_physics": "⚡ Motor Fizic",
    "tab_camera": "🎥 Cameră și Spațiu",
    "tab_system": "⚙️ Sistem și Limbi",
    "drag_hint": "⠿ Trage pentru a muta",
    "nav_prev_tab": "Tabul Anterior / Derulare Stânga",
    "nav_next_tab": "Tabul Următor / Derulare Dreapta"
  },
  "bg": {
    "physics_section": "⚡ Физика и Динамика на Сблъсъците",
    "enable_physics": "Включи Физически Двигател (Гравитация и Хвърляне)",
    "physics_floor": "Включи Колайдер на Пода",
    "physics_gravity": "Гравитация",
    "physics_elasticity": "Еластичност / Отскок",
    "physics_hint_title": "Пряк Път за Физическо Хвърляне",
    "physics_hint_body": "Задръжте D + Ляв Бутон Плъзгане за хвърляне с импулс!",
    "fps_mode_section": "🎥 Перспектива от Първо Лице и Пространствени Координати",
    "enable_fps_mode": "Включи Режим Камера от Първо Лице",
    "fps_sub": "(Превключване с Ctrl + Shift + F)",
    "fps_hint_title": "Контроли за FPS",
    "fps_hint_body": "Движете мишката за 360° изглед. WASD за движение, Наклонена черта/Интервал (Нагоре), Shift (Надолу). ESC за изход!",
    "reset_camera": "Нулирай Камерата и Позицията 🔄",
    "show_xyz_coords": "Включи Жив HUD с Пространствени Координати XYZ",
    "show_xyz_sub": "(Превключване с Ctrl + Shift + C)",
    "show_ground_grid": "Покажи 3D Референтна Мрежа на Пода",
    "xyz_hud_title": "📐 Пространствени Координати XYZ",
    "spotlight_section": "🔦 Управление на Сценични Прожектори",
    "enable_spotlight": "Включи Източник на Прожектор",
    "spotlight_angle_h": "Хоризонтален Орбитален Ъгъл",
    "spotlight_angle_v": "Вертикален Ъгъл на Издигане",
    "spotlight_cone": "Ъгъл на Конуса на Лъча",
    "spotlight_intensity": "Интензивност на Прожектора",
    "spotlight_color": "Цвят на Прожектора",
    "spotlight_color_white": "Чисто Бяло",
    "spotlight_color_gold": "Концертно Топло Злато",
    "spotlight_color_cyan": "Киберпънк Неонов Циан",
    "spotlight_color_pink": "Сценично Розово",
    "spotlight_color_red": "Лазерно Червено",
    "enable_studio_lights": "Включи Студийно Околно Осветление",
    "ambient_intensity": "Яркост на Главното Околно Осветление",
    "dark_stage_preset": "🎭 Задай Режим Тъмна Сцена",
    "add_spotlight": "➕ Добави Прожектор",
    "remove_spotlight": "🗑️ Премахни Прожектор",
    "spotlight_num": "Прожектор",
    "dual_concert_preset": "🎸 Двоен Концертен Прожектор (Злато + Циан)",
    "max_spotlights_reached": "Достигнат е максимума от 4 прожектора!",
    "tab_display": "🎯 Дисплей и Модел",
    "tab_motion": "🌀 Движение и Въртене",
    "tab_lighting": "🔦 Сценично Осветление",
    "tab_physics": "⚡ Физически Двигател",
    "tab_camera": "🎥 Камера и Пространство",
    "tab_system": "⚙️ Система и Езици",
    "drag_hint": "⠿ Плъзнете за преместване",
    "nav_prev_tab": "Предишен Раздел / Превърти Наляво",
    "nav_next_tab": "Следващ Раздел / Превърти Надясно"
  },
  "el": {
    "physics_section": "⚡ Φυσική & Δυναμική Σύγκρουσης",
    "enable_physics": "Ενεργοποίηση Μηχανής Φυσικής (Βαρύτητα & Ρίψη)",
    "physics_floor": "Ενεργοποίηση Σύγκρουσης Δαπέδου",
    "physics_gravity": "Βαρύτητα",
    "physics_elasticity": "Ελαστικότητα / Αναπήδηση",
    "physics_hint_title": "Συντόμευση Ρίψης Φυσικής",
    "physics_hint_body": "Κρατήστε D + Αριστερό Σύρσιμο για ρίψη με ορμή!",
    "fps_mode_section": "🎥 Προοπτική Πρώτου Προσώπου & Χωρικές Συντεταγμένες",
    "enable_fps_mode": "Ενεργοποίηση Λειτουργίας Κάμερας Πρώτου Προσώπου",
    "fps_sub": "(Εναλλαγή με Ctrl + Shift + F)",
    "fps_hint_title": "Χειριστήρια FPS",
    "fps_hint_body": "Μετακινήστε το ποντίκι για προβολή 360°. WASD για μετακίνηση, Διαστημόμπαρα (Πάνω), Shift (Κάτω). ESC για έξοδο!",
    "reset_camera": "Επαναφορά Κάμερας & Θέσης 🔄",
    "show_xyz_coords": "Ενεργοποίηση HUD Χωρικών Συντεταγμένων XYZ",
    "show_xyz_sub": "(Εναλλαγή με Ctrl + Shift + C)",
    "show_ground_grid": "Εμφάνιση 3D Πλέγματος Αναφοράς Δαπέδου",
    "xyz_hud_title": "📐 Χωρικές Συντεταγμένες XYZ",
    "spotlight_section": "🔦 Έλεγχος Προβολέων Σκηνής Πολλαπλών Πηγών",
    "enable_spotlight": "Ενεργοποίηση Πηγής Προβολέα",
    "spotlight_angle_h": "Οριζόντια Γωνία Τροχιάς",
    "spotlight_angle_v": "Κατακόρυφη Γωνία Ανύψωσης",
    "spotlight_cone": "Γωνία Κώνου Δέσμης",
    "spotlight_intensity": "Ένταση Προβολέα",
    "spotlight_color": "Χρώμα Προβολέα",
    "spotlight_color_white": "Καθαρό Λευκό",
    "spotlight_color_gold": "Ζεστό Χρυσό Συναυλίας",
    "spotlight_color_cyan": "Cyberpunk Νέον Κυανό",
    "spotlight_color_pink": "Ροζ Σκηνής",
    "spotlight_color_red": "Κόκκινο Λέιζερ",
    "enable_studio_lights": "Ενεργοποίηση Φωτισμού Περιβάλλοντος Στούντιο",
    "ambient_intensity": "Φωτεινότητα Κύριου Φωτός Περιβάλλοντος",
    "dark_stage_preset": "🎭 Λειτουργία Σκοτεινής Σκηνής",
    "add_spotlight": "➕ Προσθήκη Πηγής Προβολέα",
    "remove_spotlight": "🗑️ Αφαίρεση Προβολέα",
    "spotlight_num": "Προβολέας",
    "dual_concert_preset": "🎸 Διπλός Προβολέας Συναυλίας (Χρυσό + Κυανό)",
    "max_spotlights_reached": "Επιτεύχθηκε το μέγιστο όριο 4 προβολέων!",
    "tab_display": "🎯 Οθόνη & Μοντέλο",
    "tab_motion": "🌀 Κίνηση & Περιστροφή",
    "tab_lighting": "🔦 Φωτισμός Σκηνής",
    "tab_physics": "⚡ Μηχανή Φυσικής",
    "tab_camera": "🎥 Κάμερα & Χώρος",
    "tab_system": "⚙️ Σύστημα & Γλώσσες",
    "drag_hint": "⠿ Σύρετε για μετακίνηση",
    "nav_prev_tab": "Προηγούμενη Καρτέλα / Κύλιση Αριστερά",
    "nav_next_tab": "Επόμενη Καρτέλα / Κύλιση Δεξιά"
  }
};

const scriptPath = path.join(__dirname, 'scratch_create_locales.js');
let code = fs.readFileSync(scriptPath, 'utf8');

Object.keys(translationsRemaining).forEach(lang => {
  const langObjStr = `"${lang}": {`;
  if (code.includes(langObjStr)) {
    const keysObj = translationsRemaining[lang];
    const newLines = Object.keys(keysObj).map(k => `    "${k}": ${JSON.stringify(keysObj[k])}`).join(',\n');
    code = code.replace(langObjStr, `${langObjStr}\n${newLines},`);
  }
});

fs.writeFileSync(scriptPath, code, 'utf8');
console.log('✅ Injected full native translations for all remaining languages into scratch_create_locales.js');
