/**
 * Interaction State Factory Module (<90 lines)
 * Constructs two-way state proxies for viewport navigation, mouse drag tracking, modifier keys, and FPS key controls.
 */

export function createInteractionStateProxy(accessors) {
  const {
    getIsSettingsOpen, setIsSettingsOpen,
    getIsMouseOverCharacter, setIsMouseOverCharacter,
    getIsMouseOverUI, setIsMouseOverUI,
    getIsDragging, setIsDragging,
    getDragStartedOnMascot, setDragStartedOnMascot,
    getIsDraggingGear, setIsDraggingGear,
    getDragStartScreenX, setDragStartScreenX,
    getDragStartScreenY, setDragStartScreenY,
    getDragMoveDistance, setDragMoveDistance,
    getIsNavigating, setIsNavigating,
    getNavType, setNavType,
    getNavStartMouseX, setNavStartMouseX,
    getNavStartMouseY, setNavStartMouseY,
    getNavStartRotationX, setNavStartRotationX,
    getNavStartRotationY, setNavStartRotationY,
    getNavStartTranslationX, setNavStartTranslationX,
    getNavStartTranslationY, setNavStartTranslationY,
    getNavStartTranslationZ, setNavStartTranslationZ,
    getAltKeyHeld, setAltKeyHeld,
    getShiftKeyHeld, setShiftKeyHeld,
    getCtrlKeyHeld, setCtrlKeyHeld,
    getKeyDHeld, setKeyDHeld,
    getIsPhysicsDragging, setIsPhysicsDragging,
    getCameraPitch, setCameraPitch,
    getCameraYaw, setCameraYaw,
    getFpsKeyW, setFpsKeyW,
    getFpsKeyA, setFpsKeyA,
    getFpsKeyS, setFpsKeyS,
    getFpsKeyD, setFpsKeyD,
    getFpsKeySpace, setFpsKeySpace,
    getFpsKeyShift, setFpsKeyShift
  } = accessors;

  return {
    get isSettingsOpen() { return getIsSettingsOpen(); },
    set isSettingsOpen(v) { setIsSettingsOpen(v); },
    get isMouseOverCharacter() { return getIsMouseOverCharacter(); },
    set isMouseOverCharacter(v) { setIsMouseOverCharacter(v); },
    get isMouseOverUI() { return getIsMouseOverUI(); },
    set isMouseOverUI(v) { setIsMouseOverUI(v); },
    get isDragging() { return getIsDragging(); },
    set isDragging(v) { setIsDragging(v); },
    get dragStartedOnMascot() { return getDragStartedOnMascot(); },
    set dragStartedOnMascot(v) { setDragStartedOnMascot(v); },
    get isDraggingGear() { return getIsDraggingGear(); },
    set isDraggingGear(v) { setIsDraggingGear(v); },
    get dragStartScreenX() { return getDragStartScreenX(); },
    set dragStartScreenX(v) { setDragStartScreenX(v); },
    get dragStartScreenY() { return getDragStartScreenY(); },
    set dragStartScreenY(v) { setDragStartScreenY(v); },
    get dragMoveDistance() { return getDragMoveDistance(); },
    set dragMoveDistance(v) { setDragMoveDistance(v); },
    get isNavigating() { return getIsNavigating(); },
    set isNavigating(v) { setIsNavigating(v); },
    get navType() { return getNavType(); },
    set navType(v) { setNavType(v); },
    get navStartMouseX() { return getNavStartMouseX(); },
    set navStartMouseX(v) { setNavStartMouseX(v); },
    get navStartMouseY() { return getNavStartMouseY(); },
    set navStartMouseY(v) { setNavStartMouseY(v); },
    get navStartRotationX() { return getNavStartRotationX(); },
    set navStartRotationX(v) { setNavStartRotationX(v); },
    get navStartRotationY() { return getNavStartRotationY(); },
    set navStartRotationY(v) { setNavStartRotationY(v); },
    get navStartTranslationX() { return getNavStartTranslationX(); },
    set navStartTranslationX(v) { setNavStartTranslationX(v); },
    get navStartTranslationY() { return getNavStartTranslationY(); },
    set navStartTranslationY(v) { setNavStartTranslationY(v); },
    get navStartTranslationZ() { return getNavStartTranslationZ(); },
    set navStartTranslationZ(v) { setNavStartTranslationZ(v); },
    get altKeyHeld() { return getAltKeyHeld(); },
    set altKeyHeld(v) { setAltKeyHeld(v); },
    get shiftKeyHeld() { return getShiftKeyHeld(); },
    set shiftKeyHeld(v) { setShiftKeyHeld(v); },
    get ctrlKeyHeld() { return getCtrlKeyHeld(); },
    set ctrlKeyHeld(v) { setCtrlKeyHeld(v); },
    get keyDHeld() { return getKeyDHeld(); },
    set keyDHeld(v) { setKeyDHeld(v); },
    get isPhysicsDragging() { return getIsPhysicsDragging(); },
    set isPhysicsDragging(v) { setIsPhysicsDragging(v); },
    get cameraPitch() { return getCameraPitch(); },
    set cameraPitch(v) { setCameraPitch(v); },
    get cameraYaw() { return getCameraYaw(); },
    set cameraYaw(v) { setCameraYaw(v); },
    get fpsKeyW() { return getFpsKeyW(); },
    set fpsKeyW(v) { setFpsKeyW(v); },
    get fpsKeyA() { return getFpsKeyA(); },
    set fpsKeyA(v) { setFpsKeyA(v); },
    get fpsKeyS() { return getFpsKeyS(); },
    set fpsKeyS(v) { setFpsKeyS(v); },
    get fpsKeyD() { return getFpsKeyD(); },
    set fpsKeyD(v) { setFpsKeyD(v); },
    get fpsKeySpace() { return getFpsKeySpace(); },
    set fpsKeySpace(v) { setFpsKeySpace(v); },
    get fpsKeyShift() { return getFpsKeyShift(); },
    set fpsKeyShift(v) { setFpsKeyShift(v); }
  };
}
